import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const faqs = [
  {
    question: "What is Lovable?",
    answer: "Lovable is an AI-powered software development platform that enables anyone to create software, regardless of their technical background. It uses advanced AI to assist in coding, design, and project management."
  },
  {
    question: "Do I need coding experience to use Lovable?",
    answer: "While coding experience can be helpful, Lovable is designed to be accessible to users with various levels of technical expertise. Our AI assistant can guide you through the development process and generate code based on your instructions."
  },
  {
    question: "How does the AI software engineer work?",
    answer: "Our AI software engineer uses advanced machine learning models to understand your project requirements, generate code, suggest optimizations, and help with debugging. It learns from vast amounts of code and best practices to provide intelligent assistance throughout the development process."
  },
  {
    question: "Is the code generated by Lovable secure and efficient?",
    answer: "Yes, Lovable prioritizes security and efficiency. Our AI is trained on best practices and regularly updated security standards. Additionally, the platform includes built-in security checks and optimization suggestions to ensure the code is both secure and performant."
  },
  {
    question: "Can Lovable integrate with existing development tools and workflows?",
    answer: "Absolutely! Lovable is designed to complement your existing tools and workflows. It can integrate with popular version control systems, CI/CD pipelines, and project management tools to seamlessly fit into your development process."
  }
]

export default function FAQ() {
  return (
    <section className="py-24 sm:py-32" id="faq">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:text-center">
          <h2 className="text-base font-semibold leading-7 text-primary">FAQ</h2>
          <p className="mt-2 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Frequently Asked Questions
          </p>
          <p className="mt-6 text-lg leading-8 text-muted-foreground">
            Got questions? We've got answers. If you don't see your question here, feel free to contact us.
          </p>
        </div>
        <div className="mx-auto mt-16 max-w-2xl">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger>{faq.question}</AccordionTrigger>
                <AccordionContent>{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  )
}