import { motion } from 'framer-motion'
import { Card, CardContent } from '@/components/ui/card'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'

const testimonials = [
  {
    content: "Lovable has transformed the way we develop software. It's like having an AI-powered co-pilot for coding!",
    author: "Alex Johnson",
    role: "CTO, TechInnovate",
    avatar: "/api/placeholder/40/40"
  },
  {
    content: "As a non-technical founder, Lovable has been a game-changer. I can now bring my ideas to life without extensive coding knowledge.",
    author: "Sarah Lee",
    role: "Founder, StartupX",
    avatar: "/api/placeholder/40/40"
  },
  {
    content: "The speed and quality of code generated by Lovable are impressive. It has significantly reduced our development time.",
    author: "Michael Chen",
    role: "Lead Developer, CodeCraft",
    avatar: "/api/placeholder/40/40"
  }
]

export default function Testimonials() {
  return (
    <section className="py-24 sm:py-32 bg-secondary" id="testimonials">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-xl text-center">
          <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
            Loved by developers and founders alike
          </h2>
          <p className="mt-6 text-lg leading-8 text-muted-foreground">
            Don't just take our word for it. Here's what our users have to say about Lovable.
          </p>
        </div>
        <div className="mx-auto mt-16 flow-root max-w-2xl sm:mt-20 lg:mx-0 lg:max-w-none">
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {testimonials.map((testimonial, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 50 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
              >
                <Card>
                  <CardContent className="p-6">
                    <p className="text-lg font-semibold text-foreground">{testimonial.content}</p>
                    <div className="mt-6 flex items-center">
                      <Avatar>
                        <AvatarImage src={testimonial.avatar} alt={testimonial.author} />
                        <AvatarFallback>{testimonial.author.split(' ').map(n => n[0]).join('')}</AvatarFallback>
                      </Avatar>
                      <div className="ml-4">
                        <p className="text-base font-semibold text-foreground">{testimonial.author}</p>
                        <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}